Repository Magnatikk/FastTurboBoost, pull requests merged in 2023-07, with the labels that each got.

#6 Carrosserie ftb
  Carrosserie.js
Labels: bug

#4 Vb dragonfield patch 1
  README.md
Labels: documentation, enhancement

#1 Create template.md
  .github/pull_request_template/template.md
Labels: enhancement

#26 Update action.yml
  .github/workflows/action.yml
Labels: enhancement

#18 Ia ftb
  .github/ISSUE_TEMPLATE/new-commit.md
  IA_basic_tic-tac-toe.c
Labels: enhancement, Adding

#22 Create Gestion_climatisation.c
  Gestion_climatisation.c
Labels: enhancement, Adding

#24 Create Déplacement_FTB.c
  Déplacement_FTB.c
Labels: enhancement, Adding

#29 Dev ftb
  .github/workflows/action.yml
  Carrosserie.js
  Couleur_Turbo_dynamique.py
  Déplacement_FTB.c
  Freins-Ceramique.c
  Gestion_climatisation.c
  IA_basic_tic-tac-toe.c
  Ligne-Custom.c
  Loi_basic.c
  Moteur_FTB_function.c
  Phare-Xenon.c
  Turbo-Compresseur.c
  carrosserie.c
Labels: enhancement, Adding
